<form class="search-container" action=<?= $this->baseUrl() . '/public/search'?>>
	<div class="search-container-wrap">
		<select name=<?=$this->element->category->getAttrib('name')?>>
			<?php foreach($this->element->category->getMultiOptions() as $option) : ?>

			<option>
				<?php echo $option?>
			</option>

			<?php endforeach;?>		
		</select>
		<input type="text" name=<?php echo $this->element->input->getAttrib('name')?> placeholder = "Search">
		 <button class="search-button"><i class="fa fa-search"></i></button>
	</div>

</form>
