<div class="content">
	<div class="content-wrapper">
				
		<div class="content-element">
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Info</a>
						</div>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Info</a>
						</div>
					</div>	
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Info</a>
						</div>
					</div>	
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Info</a>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>
 <?= $this->headScript()->appendFile($this->baseUrl() . '/js/item_anim.js'); ?>