<?php
$this->title = "Le Aziende";
$this->headTitle($this->title);
?>

<table>
<tr>
<th>Nome</th>
<th>Emal</th>
<th>SitoWeb</th>
<th>Descrizione</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->aziende as $azienda) : ?>
<tr>
<td><?php echo $this->escape($azienda->Nome);?></td>
<td><?php echo $this->escape($azienda->Emal);?></td>
<td><?php echo $this->escape($azienda->SitoWeb);?></td>
<td><?php echo $this->escape($azienda->Descrizione);?></td>


</td>
</tr>
<?php endforeach; ?>
</table>
