<div class="search-container">
	<div class="search-container-wrap">
		<select>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
		</select>
		<input type="text" name="Search" placeholder="Search">
		<button class="search-button"><i class="fa fa-search"></i></button>
	</div>
</div>

<div class="content">
	<div class="content-wrapper">
		<div class="content-element">

			<?php foreach($this->company as $company) : ?>

				<div class="item">
					<div class="inner">
						<div class="wrapper">
							<img src="http://placehold.it/400x300">
								<div class="coupon-info">
									<span style="">
									<?php echo $this->escape($company->name);?>
									<?php echo $this->escape($company->email);?>
									<?php echo $this->escape($company->website);?>
									<?php echo $this->escape($company->phone);?>
									<?php echo $this->escape($company->address);?>
									<?php echo $this->escape($company->category);?>
									<?php echo $this->escape($company->description);?>	
									</span>
									<button class="coupon-button">Info</a>	
									
								</div>
						</div>
					</div>
				</div>

			<?php endforeach; ?>

		</div>
	</div>
</div>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/modal.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/js/item_anim.js'); ?>
