<?php
$this->title = "company";
$this->headTitle($this->title);
?>

<table>
<tr>
<th>Name</th>
<th>Email</th>
<th>Website</th>
<th>Phone</th>
<th>Address</th>
<th>Category</th>
<th>Description</th>
<th>Img</th>

<th>&nbsp;</th>
</tr>
<?php foreach($this->company as $company) : ?>
<tr>
<td><?php echo $this->escape($company->name);?></td>
<td><?php echo $this->escape($company->email);?></td>
<td><?php echo $this->escape($company->website);?></td>
<td><?php echo $this->escape($company->phone);?></td>
<td><?php echo $this->escape($company->address);?></td>
<td><?php echo $this->escape($company->category);?></td>
<td><?php echo $this->escape($company->description);?></td>
<td><?php echo $this->escape($company->img);?></td>



</td>
</tr>
<?php endforeach; ?>
</table>
