
<?php foreach($this->coupon as $coupon) : ?>

<?php echo $this->escape($coupon->Nome);?>
<?php echo $this->escape($coupon->Azienda);?>
<?php echo $this->escape($coupon->DataInizio);?>
<?php echo $this->escape($coupon->DataFine);?>
<?php echo $this->escape($coupon->Quantità);?>
<?php echo $this->escape($coupon->Tipologia);?>
<?php echo $this->escape($coupon->Sconto);?>
<?php echo $this->escape($coupon->PrezzoIniziale);?>
<?php echo $this->escape($coupon->PrezzoFinale);?>

<?php endforeach; ?>

