<html>
<head>

</head>
<body>
<div class="content-container">
		<h2 class="title">F.A.Q</h2>
		<ol class="faq-list">
		
			<li>
				<div class="content-title">
					<h4>Sono già un utente registrato, come posso accedere al mio account personale? </h4>
					<h5> Clicca su “Login” in alto a destra della pagina Home e inserisci il tuo nome utente e password. </h5>
				</div>					
			</li>
			
			<li>
				<div class="content-title">
					<h4>Hai scordato la tua password?</h4>
					<h5>Rivolgiti agli amministratori del sito tramite uno dei contatti che troverai in fondo ad ogni pagina del sito. </h5>
				</div>				
			</li>
			
			<li>
				<div class="content-title">
					<h4>Come posso scaricare un coupon? </h4>					
					<h5>Stampa del coupon completamente gratuito e pagamento diretto presso il Partner. Per godere dell’offerta indicata sul coupon, devi semplicemente stampare quest’ultimo e recarti presso il punto vendita o l’attività dove effettuerai direttamente il pagamento, secondo le modalità accettate dal Partner, senza alcun bisogno di pagamento online con carta di credito.</h5>
				</div>
			</li>
			
			<li>
				<div class="content-title">
					<h4>Quanto tempo ho per utilizzare il mio coupon?</h4>
					<h5>La validità del coupon è chiaramente indicata sul coupon stesso.</h5>
				</div>	
			</li>
			
			<li>			
				<div class="content-title">
					<h4>Devo essere registrato per poter usufruire di un coupon?</h4>
					<h5>Si, dopo la registrazione potrai stampare il coupon con relativo codice da presentare al negozio che ha emesso l’offerta</h5>
				</div>	
			</li>
			
			<li>
				<div class="content-title">
					<h4>Posso stampare più coupon uguali per usufruire di maggiore sconto?</h4>
					<h5>No, per ogni utente è possibile la stampa di un solo coupon per ogni promozione.</h5>
				</div>	
			</li>
			
			<li>				
				<div class="content-title">
					<h4>Quanti coupon posso stampare in una volta?</h4>
					<h5>Non ci sono limiti al numero di coupon stampabili in una sola volta, uno per ogni coupon.</h5>
				</div>
			</li>
			
			<li>
				<div class="content-title">
					<h4>Sono già registrato ma come faccio a cambiare i miei dati personali?<h4>
					<h5>Accedi all’area riservata in alto a destra dove troverai la procedura per modificare i tuoi dati.</h5>
				</div>
			</li>
		</ol>

	</div>

</body>
</html>