

<!--<div class="search-container">
	<div class="search-container-wrap">
		<select>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
		</select>
		<input type="text" name="Search" placeholder="Search">
		<button class="search-button"><i class="fa fa-search"></i></button>
	</div>
	<div class="info">
		<span>Just Search</span>
	</div>
</div>-->
<div class="content">
		<i class="fa fa-close close-btn" style="color:black;position:relative;left:98%;font-size:1.3rem"></i>
		<div class="content-wrapper">
				
		<div class="content-element">
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Acquistare</a>
						</div>
					</div>
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Acquistare</a>
						</div>
					</div>	
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Acquistare</a>
						</div>
					</div>	
				</div>
			</div>
			<div class="item">
				<div class="inner">
					<div class="wrapper">
						<img src="http://placehold.it/400x300">
						<div class="coupon-info">
							<span style="">Descrizione</span>
							<a href="" class="coupon-link" style="">Acquistare</a>
						</div>
					</div>	
				</div>
			</div>
		</div>
	</div>
	</div>