<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
	var formName='<?= $this->loginForm->getName() ?>';
	$(":input").on('blur', function(event) {
    var formElementId = $(this).attr('id');
    doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<div class="static">
 <h3>login</h3>
 <p>Utilizza questa form per l'autenticazione</p>
 <?=$this->loginForm; ?>
</div>
