<div class="content">
	<div class="content-wrapper">
		<div class="content-element">

			<?php foreach($this->promotion as $promotion) : ?>

				<div class="item">
					<div class="inner">
						<div class="wrapper">
							<img src="http://placehold.it/400x300">
								<div class="coupon-info">
									<span style="">
									<?php echo $this->escape($promotion->company);?>
									<?php echo $this->escape($promotion->datebegin);?>
									<?php echo $this->escape($promotion->datefine);?>
									<?php echo $this->escape($promotion->category);?>
									<?php echo $this->escape($promotion->description);?>
									<?php echo $this->escape($promotion->price);?>	
									</span>
									<a href="" class="coupon-link">Acquistare</a>		
									
								</div>
						</div>
					</div>
				</div>

			<?php endforeach; ?>

		</div>
	</div>
</div>
