<form>
<div style="background-color: white">
	<span>Sono state trovate</span>
</div>
<div style="display: flex;background-color: white;flex-direction: column;">
<span style="align-self: center;">Aziende</span>
	<div class="filter" style ="display: flex;
	    justify-content: space-around;
	    background-color: white;">
	    <?php foreach ($this->companies as $company) : ?>
		<label><input type="checkbox" checked><?=$company->company?></label>
		<?php endforeach ?>
	</div>
</div>
<?php if($this->categories!=null) : ?>
<div style="display: flex;background-color: white;flex-direction: column;">
<span style="width:100%;text-align: center;">Categorie</span>
	<div class="filter" style ="display: flex;
	    justify-content: space-around;
	    background-color: white;">	  
	    <?php foreach ($this->categories as $category) : ?>
		<label><input type="checkbox" checked><?=$category->category?></label>
		<?php endforeach ?>
	</div>
</div>
<?php endif ?>
</form>
<div class="content">
	<div class="content-wrapper">
		<div class="content-element">

			<?php foreach($this->promotion as $promotion) : ?>

				<div class="item">
					<div class="inner">
						<div class="wrapper">
							<img src=<?= ($this->baseUrl() . "/img/" . $this->escape($promotion->img))?>>
								<div class="coupon-info">
									<span style="">
									<?php echo $this->escape($promotion->price);?>	
									</span>
									<button class="coupon-button">Info</a>		
								</div>
						 		<div class="item-popup">
						 			<i class="fa fa-close close-item-popup" style="color:black;position:relative;left:96%;top:5px;font-size:1.3rem"></i>
									<span><?php echo $this->escape($promotion->company);?></span>

									<div class="description">
										<span><?php echo $this->escape($promotion->description);?></span>
									</div>

						 			<div class="date-wrapper">

						 				<div class = "date">
						 					<span>Data di Inizio</span>
						 					<span><?php echo $this->escape($promotion->datebegin);?></span>	
						 				</div>

										<div class="date">
											<span>Data della fine</span>
											<span><?php echo $this->escape($promotion->datefine);?></span>						 			
										</div>

						 			</div>

						 			<div class="links">
										<a href="">Azienda</a>										
										<a href="">Acquistare</a>
									</div>

								</div>
						</div>
					</div>
				</div>

			<?php endforeach; ?>

		</div>
	</div>
</div>
 <?= $this->headScript()->appendFile($this->baseUrl() . '/js/item_anim.js'); ?>
 <?= $this->headScript()->appendFile($this->baseUrl() . '/js/modal.js'); ?>