<br /><br />
<div id="view-content">
	<p>Benvenuto nella nuova versione del sito web “Coupons”, il portale che permette di scaricare gratis le promozioni con i coupon che le aziende mettono a disposizione.
<br></br>Risparmio:<br></br>
Da anni un punto di riferimento per i risparmiatori dove possono trovare facilmente i buoni sconto, i codici sconto per acquisti nei negozi online ed i coupon per i negozi fisici inseriti autonomamente dalle aziende, o ancora promozioni, regali, tutorial, premi sicuri e tutto ciò che è legato al mondo del risparmio su tantissimi servizi e prodotti. In pochi secondi puoi trovare quello che desideri utilizzando la barra di ricerca, inserendo il nome del prodotto e/o la categoria.
<br></br>Il funzionamento:<br></br>
L’utente potrà sfogliare tra i negozi presenti, le categorie o più rapidamente nel motore di ricerca interno, trovare la promozione che più lo soddisfa, stampare il voucher o presentarlo con il cellulare in cassa pagando direttamente il commerciante con la scontistica riportata. Potrà anche trovare il negozio preferito con tutte le promozioni in corso di validità. Un vero e proprio mini sito delle aziende dove potranno inserire i coupon in modo facile.
<br></br>Registrazione:<br></br>
Per cominciare a risparmiare su “Coupons” dovrai registrarti al sito, in alto a destra puoi trovare il pulsante per la registrazione e quello del login che poi ti servirà per gestire il tuo account. Cliccando su “Registrati” ti comparirà una pagina dove saranno presenti la form per la registrazione, se sei titolare di un negozio contattaci per inserire la tua azienda. Ecco fatto, una volta creato l’account puoi cominciare a scaricare gli sconti di tuo interesse.
</p>
</div>