<?php echo $this->doctype() ?>
<html>
<head>
	<?= $this->headMeta(); ?>
    <?= $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css'); ?>
    <?= $this->headLink()->appendStylesheet("https://fonts.googleapis.com/css?family=Lobster|Montserrat|Ropa+Sans") ?>
    <?= $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome-4.7.0/css/font-awesome.min.css') ?>
    <?= $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-3.2.1.min.js'); ?>
    <?= $this->headTitle(); ?>

</head>
<body>


	
	<!-- end #header -->
	<nav>
		<?= $this->render('_topnavmain.phtml') ?>
	</nav>
	<!-- end #menu -->
	  	  <?php echo $this->layout()->content; ?>
	  	  
    <?= $this->headScript()->appendFile($this->baseUrl() . '/js/search_script.js'); ?>

	<!-- end #content -->
	<div id="footer">
		<br>
		<p>Project</p>
	</div>
	<!-- end #footer -->
</div>
</body>
</html>
