<?php echo $this->doctype() ?>

<html>
<head>
	<?php $this->headMeta(); ?>

    <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/styles.css'); ?>
    <?php $this->headLink()->prependStylesheet("https://fonts.googleapis.com/css?family=Lobster|Montserrat|Ropa+Sans"); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/font-awesome-4.7.0/css/font-awesome.min.css'); ?>
    <?= $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-3.2.1.min.js'); ?>
    <script type="text/javascript" source = "https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <?= $this->headTitle(); ?>
    
        <?php

    	$style=""; 
    	if($this->page_name == 'promotion'){$style = "promotion_page.css";}
    	
    	else if($this->page_name == 'company'){$style = "company_page.css";}
    	
    	echo $this->headLink()->appendStylesheet($this->baseUrl() .'/css/' . $style);
    	  	?>

</head>
<body>


	<!-- end #header -->
	<nav>
		<?= $this->render('_topnavmain.phtml') ?>
	</nav>
	<!-- end #menu -->
	  	  <?php echo $this->layout()->content; ?>

  </body>
</body>

</html>
