<?php echo $this->doctype() ?>
<html>
<head>
	<?= $this->headMeta(); ?>
    <?= $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css'); ?>
    <?= $this->headLink()->appendStylesheet("https://fonts.googleapis.com/css?family=Lobster|Montserrat|Ropa+Sans") ?>
    <?= $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome-4.7.0/css/font-awesome.min.css') ?>
    <?= $this->headTitle(); ?>
</head>
<body>


	
	<!-- end #header -->
	<nav>
		<?= $this->render('_topnavmain.phtml') ?>
	</nav>
	<!-- end #menu -->
  	  <div id="bottom">
    	<div id="bottom">
	  	  <?php echo $this->layout()->content; ?>
	    </div>
  	  </div>


	<!-- end #content -->
	<div id="footer">
		<br>
		<p>Project</p>
	</div>
	<!-- end #footer -->
</div>
</body>
</html>
