<!--<form class="search-container">
	<div class="search-container-wrap">
		<select>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
			<option>Item</option>
		</select>
		<input type="text" name="Search" placeholder="Search">
		<button class="search-button"><i class="fa fa-search"></i></button>
	</div>
</form>
-->
<?=$this->searchForm; ?>