<?php echo $this->doctype() ?>
<html>
<head>
	<?php $this->headMeta(); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css'); ?>
    <?php $this->headLink()->appendStylesheet("https://fonts.googleapis.com/css?family=Lobster|Montserrat|Ropa+Sans"); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/font-awesome-4.7.0/css/font-awesome.min.css'); ?>
    <?= $this->headScript()->prependFile($this->baseUrl() . '/js/jquery-3.2.1.min.js'); ?>
    <?= $this->headTitle(); ?>
</head>
<body>


	<!-- end #header -->
	<nav>
		<?= $this->render('_topnavmain_user.phtml') ?>
	</nav>
	<!-- end #menu -->
	  	  <?php echo $this->layout()->content; ?>
	  	  

</div>
</body>
</html>